export class Articulo {
    cod_Barras?: string;
    descripcion_Corta?: string;
    id_Clasificacion?: any;
    articulo_Disponible?: string;
    last_Update_Inventory?: string;
    stock_Min?: string;
    cod_nterno?: any;
    descripcion?: string;
    precio_Venta?: string;
    stock_Max?: string;
    cantidad_Um?: string;
    precio_Compra?: string;
    utilidad?: string;
    cod_Asociado?: any;
    id_Unidad?: string;
    id_Proveedor?: string;
    tipo_Articulo?: string;
    stock?: string;
    kit?: string;
    iva?: string;
    activo?: any;
    kit_Fecha_Ini?: any;
    visible?: string;
    fecha_Registro?: string;
    kit_Fecha_Fin?: any;
    cve_Producto?: string;
    puntos?: string;
}
